### ISSUE TITLE
onOk: { ... this.dialog ... } -> unused vaiable?

### ISSUE THREAD

**Issue by rowild** [ckeditor/ckeditor-docs-samples#4]
I wonder why there is a var this.dialog? It seems to unused... (the tutorial 1 on that plugin uses a different approach in the end, where it is indeed used, but the solution here makes it superfluous, I guess...)

```
CKEDITOR.dialog.add('abbrDialog', function (editor) {
return {
onOk: function() {

// The context of this function is the dialog object itself.
// http://docs.ckeditor.com/#!/api/CKEDITOR.dialog
// ...but it is not needed...?
var dialog = this;
}
}
}
```

Any explanation would be greatly appreciated!
Thanks!
Robert

**Comment by Reinmar** [comment]
I guess this is just a leftover. This tutorial had been written a log time ago and has been changed many times since then :).

The other option is that it was defined there as a hint that one can easily access the dialog instance. There are many developers new to JavaScript and the context is always confusing at the beginning.

In any case, we need to clarify this, so thanks for reporting.
