### ISSUE TITLE
Document Editor Issues

### ISSUE THREAD

**Issue by 2braincells2go** [ckeditor/ckeditor-docs-samples#7]
Hi.

I download and try the sample document editor. Works great out of box but, wishing to use local copy of ckeditor (not CDN).

The docs at http://docs.ckeditor.com/#!/guide/dev_example_setups say based on full package so I download full package and change https://cdn.ckeditor.com/4.6.1/full-all/ckeditor.js to my local copy of ckeditor like:

`<script src="ckeditor/ckeditor.js"></script>`

My current directory layout is:

ckeditor
index.html
mystyle.css

The editor now loads nonfunctional like:

![image](https://cloud.githubusercontent.com/assets/2567500/22677999/83ac0f98-ecbc-11e6-8725-424e994f2319.png)

No errors in dev console (except upload which is expected).

Is this bug? Seems like must be if using the full editor and samples?

Thanks!

**Comment by f1ames** [comment]
Hi @2braincells2go,
this sample utilizes 3 more plugins which are not included in the Full preset (https://github.com/ckeditor/ckeditor-docs-samples/blob/master/editors/document-editor/index.html#L112): `tableresize`, `uploadfile`, `uploadimage`. You may use [online builder](http://ckeditor.com/builder) to add them to a Full preset and it should work fine.
There is a difference in number of plugins included by default between Full and Full-All preset so that is the case here.

**Comment by 2braincells2go** [comment]
Thanks but I built and added those plugins as page stated. Does not work.

**Comment by wwalc** [comment]
Can you put your broken example online somewhere? We'll check what's wrong.

**Comment by 2braincells2go** [comment]
Sure thing, can upload:

http://wptestbed.ml/ckeditor/

Appreciate any input.

Thanks!

**Comment by wwalc** [comment]
![screen shot 2017-02-07 at 18 34 24](https://cloud.githubusercontent.com/assets/545175/22703322/14ae3960-ed64-11e6-82b4-35d53097706b.png)

**Comment by 2braincells2go** [comment]
Sorry, I cannot see the site down. Loads for me. Not sure what issue would be unless you are in country which is blocked..

http://www.downforeveryoneorjustme.com/http://wptestbed.ml/ckeditor/

So I guess just forget but appreciate you trying.

All I did was build directly from CKEditor site using full, nothing extra. Added to directory with the sample document editor files.
